"""
Internal curated FFXIV farm data.

Provides seed data for collection_catalog_items so the catalog is useful
immediately without requiring a FFXIV Collect API sync.

source_duty_key MUST match the trial_id from MOUNT_FARM_CATALOG (mount_farms.py)
so that static farm progress bridges correctly to Player Hub suggestions.
"""

from typing import TypedDict


class CuratedItem(TypedDict, total=False):
    source_key: str          # Unique internal key (used as external_id)
    name: str                # Reward display name
    category: str            # mount / weapon / orchestrion / minion / other
    expansion: str           # arr / hw / sb / shb / ew / dt
    patch: str               # e.g. "7.0"
    source_type: str         # extreme / ultimate / other
    source_duty_name: str    # Human-readable duty name
    source_duty_key: str     # Must match trial_id in MOUNT_FARM_CATALOG for Player Hub sync
    source_text: str         # Full source description
    token_name: str | None   # Currency/totem name, or None if no exchange
    token_cost: int | None   # Cost in tokens, or None if no exchange
    notes: str | None        # Extra notes


# ── Dawntrail (7.x) ───────────────────────────────────────────────────────────

DAWNTRAIL_EXTREME_MOUNTS: list[CuratedItem] = [
    {
        "source_key": "dt-ex2-mount",
        "name": "Wings of Ruin",
        "category": "mount",
        "expansion": "dt",
        "patch": "7.0",
        "source_type": "extreme",
        "source_duty_name": "Worqor Lar Dor (Extreme)",
        "source_duty_key": "dt-valigarmanda",
        "source_text": "Worqor Lar Dor (Extreme) — Valigarmanda",
        "token_name": "Skyruin Totem",
        "token_cost": 99,
        "notes": None,
    },
    {
        "source_key": "dt-ex3-mount",
        "name": "Wings of Resolve",
        "category": "mount",
        "expansion": "dt",
        "patch": "7.0",
        "source_type": "extreme",
        "source_duty_name": "Everkeep (Extreme)",
        "source_duty_key": "dt-zoraal-ja",
        "source_text": "Everkeep (Extreme) — Zoraal Ja",
        "token_name": "Resilient Totem",
        "token_cost": 99,
        "notes": None,
    },
    {
        "source_key": "dt-ex4-mount",
        "name": "Wings of Eternity",
        "category": "mount",
        "expansion": "dt",
        "patch": "7.1",
        "source_type": "extreme",
        "source_duty_name": "The Minstrel's Ballad: Sphene's Burden",
        "source_duty_key": "dt-sphene",
        "source_text": "The Minstrel's Ballad: Sphene's Burden",
        "token_name": "Totem Eternal",
        "token_cost": 99,
        "notes": None,
    },
    {
        "source_key": "dt-ex5-mount",
        "name": "Wings of the Knighthood",
        "category": "mount",
        "expansion": "dt",
        "patch": "7.2",
        "source_type": "extreme",
        "source_duty_name": "Recollection (Extreme)",
        "source_duty_key": "dt-recollection",
        "source_text": "Recollection (Extreme)",
        "token_name": "Knight Totem",
        "token_cost": 99,
        "notes": None,
    },
    {
        "source_key": "dt-ex6-mount",
        "name": "Wings of Death",
        "category": "mount",
        "expansion": "dt",
        "patch": "7.2",
        "source_type": "extreme",
        "source_duty_name": "The Minstrel's Ballad: Necron's Embrace",
        "source_duty_key": "dt-necron-embrace",
        "source_text": "The Minstrel's Ballad: Necron's Embrace",
        "token_name": "Grave Totem",
        "token_cost": 99,
        "notes": None,
    },
    {
        "source_key": "dt-ex7-mount",
        "name": "Felyne Support Team Cart Horn",
        "category": "mount",
        "expansion": "dt",
        "patch": "7.2",
        "source_type": "extreme",
        "source_duty_name": "The Windward Wilds (Extreme)",
        "source_duty_key": "dt-windward-wilds",
        "source_text": "The Windward Wilds (Extreme) — Arkveld (Monster Hunter Collab)",
        "token_name": "Guardian Arkveld Certificate",
        "token_cost": 99,
        "notes": None,
    },
    {
        "source_key": "dt-ex8-mount",
        "name": "Wings of Mist",
        "category": "mount",
        "expansion": "dt",
        "patch": "7.25",
        "source_type": "extreme",
        "source_duty_name": "Hell on Rails (Extreme)",
        "source_duty_key": "dt-hell-on-rails",
        "source_text": "Hell on Rails (Extreme)",
        "token_name": None,
        "token_cost": None,
        "notes": "Totem exchange not yet available",
    },
    {
        "source_key": "dt-ex9-mount",
        "name": "Wings of Nihility",
        "category": "mount",
        "expansion": "dt",
        "patch": "7.25",
        "source_type": "extreme",
        "source_duty_name": "The Unmaking (Extreme)",
        "source_duty_key": "dt-unmaking",
        "source_text": "The Unmaking (Extreme)",
        "token_name": None,
        "token_cost": None,
        "notes": "Totem exchange not yet available",
    },
]

DAWNTRAIL_ULTIMATE_WEAPONS: list[CuratedItem] = [
    {
        "source_key": "dt-ult1-weapons",
        "name": "Ultimate Edenmorn Weapons",
        "category": "weapon",
        "expansion": "dt",
        "patch": "7.0",
        "source_type": "ultimate",
        "source_duty_name": "Futures Rewritten (Ultimate)",
        "source_duty_key": "ult-fru",
        "source_text": "Futures Rewritten (Ultimate) — Oracle of Darkness",
        "token_name": "Oracle Totem",
        "token_cost": 7,
        "notes": None,
    },
    {
        "source_key": "dt-ult2-weapons",
        "name": "Palazzo Diamond Weapons",
        "category": "weapon",
        "expansion": "dt",
        "patch": "7.2",
        "source_type": "ultimate",
        "source_duty_name": "Dancing Mad (Ultimate)",
        "source_duty_key": "ult-dmu",
        "source_text": "Dancing Mad (Ultimate) — The Emperor",
        "token_name": "Mad Harlequin's Totem",
        "token_cost": 7,
        "notes": None,
    },
]

# ── Endwalker (6.x) ───────────────────────────────────────────────────────────

ENDWALKER_EXTREME_MOUNTS: list[CuratedItem] = [
    {
        "source_key": "ew-ex1-mount",
        "name": "Lynx of Fallen Shadow",
        "category": "mount",
        "expansion": "ew",
        "patch": "6.0",
        "source_type": "extreme",
        "source_duty_name": "The Dark Inside (Extreme)",
        "source_duty_key": "ew-zodiark",
        "source_text": "The Dark Inside (Extreme) — Zodiark",
        "token_name": "Zodiark Totem",
        "token_cost": 99,
        "notes": None,
    },
    {
        "source_key": "ew-ex2-mount",
        "name": "Lynx of Divine Light",
        "category": "mount",
        "expansion": "ew",
        "patch": "6.0",
        "source_type": "extreme",
        "source_duty_name": "The Mothercrystal (Extreme)",
        "source_duty_key": "ew-hydaelyn",
        "source_text": "The Mothercrystal (Extreme) — Hydaelyn",
        "token_name": "Hydaelyn Totem",
        "token_cost": 99,
        "notes": None,
    },
    {
        "source_key": "ew-ex3-mount",
        "name": "Lynx of Eternal Darkness",
        "category": "mount",
        "expansion": "ew",
        "patch": "6.1",
        "source_type": "extreme",
        "source_duty_name": "The Final Day (Extreme)",
        "source_duty_key": "ew-endsinger",
        "source_text": "The Final Day (Extreme) — Endsinger",
        "token_name": "Endsinger Totem",
        "token_cost": 99,
        "notes": None,
    },
    {
        "source_key": "ew-ex4-mount",
        "name": "Lynx of Imperial Sorrow",
        "category": "mount",
        "expansion": "ew",
        "patch": "6.2",
        "source_type": "extreme",
        "source_duty_name": "Storm's Crown (Extreme)",
        "source_duty_key": "ew-barbariccia",
        "source_text": "Storm's Crown (Extreme) — Barbariccia",
        "token_name": "Barbariccia Totem",
        "token_cost": 99,
        "notes": None,
    },
    {
        "source_key": "ew-ex5-mount",
        "name": "Lynx of Abyssal Grief",
        "category": "mount",
        "expansion": "ew",
        "patch": "6.3",
        "source_type": "extreme",
        "source_duty_name": "Mount Ordeals (Extreme)",
        "source_duty_key": "ew-rubicante",
        "source_text": "Mount Ordeals (Extreme) — Rubicante",
        "token_name": "Rubicante Totem",
        "token_cost": 99,
        "notes": None,
    },
    {
        "source_key": "ew-ex6-mount",
        "name": "Lynx of Righteous Fire",
        "category": "mount",
        "expansion": "ew",
        "patch": "6.4",
        "source_type": "extreme",
        "source_duty_name": "The Voidcast Dais (Extreme)",
        "source_duty_key": "ew-golbez",
        "source_text": "The Voidcast Dais (Extreme) — Golbez",
        "token_name": "Golbez Totem",
        "token_cost": 99,
        "notes": None,
    },
    {
        "source_key": "ew-ex7-mount",
        "name": "Lynx of Imperious Wind",
        "category": "mount",
        "expansion": "ew",
        "patch": "6.5",
        "source_type": "extreme",
        "source_duty_name": "The Abyssal Fracture (Extreme)",
        "source_duty_key": "ew-zeromus",
        "source_text": "The Abyssal Fracture (Extreme) — Zeromus",
        "token_name": "Zeromus Totem",
        "token_cost": 99,
        "notes": None,
    },
]

ENDWALKER_ULTIMATE_WEAPONS: list[CuratedItem] = [
    {
        "source_key": "ew-ult1-weapons",
        "name": "Ultimate Weapons of the Heavens",
        "category": "weapon",
        "expansion": "ew",
        "patch": "6.11",
        "source_type": "ultimate",
        "source_duty_name": "Dragonsong's Reprise (Ultimate)",
        "source_duty_key": "ult-dsr",
        "source_text": "Dragonsong's Reprise (Ultimate) — King Thordan",
        "token_name": "Dragonsong Totem",
        "token_cost": 7,
        "notes": None,
    },
    {
        "source_key": "ew-ult2-weapons",
        "name": "Ultimate Omega Weapons",
        "category": "weapon",
        "expansion": "ew",
        "patch": "6.31",
        "source_type": "ultimate",
        "source_duty_name": "The Omega Protocol (Ultimate)",
        "source_duty_key": "ult-top",
        "source_text": "The Omega Protocol (Ultimate) — Omega",
        "token_name": "Omega Totem",
        "token_cost": 7,
        "notes": None,
    },
]

# ── Shadowbringers (5.x) ──────────────────────────────────────────────────────

SHADOWBRINGERS_EXTREME_MOUNTS: list[CuratedItem] = [
    {
        "source_key": "shb-titania-mount",
        "name": "Titania",
        "category": "mount",
        "expansion": "shb",
        "patch": "5.0",
        "source_type": "extreme",
        "source_duty_name": "The Dancing Plague (Extreme)",
        "source_duty_key": "shb-titania",
        "source_text": "The Dancing Plague (Extreme) — Titania",
        "token_name": "Fae Totem",
        "token_cost": 99,
        "notes": None,
    },
    {
        "source_key": "shb-innocence-mount",
        "name": "Innocence",
        "category": "mount",
        "expansion": "shb",
        "patch": "5.0",
        "source_type": "extreme",
        "source_duty_name": "The Crown of the Immaculate (Extreme)",
        "source_duty_key": "shb-innocence",
        "source_text": "The Crown of the Immaculate (Extreme) — Innocence",
        "token_name": "Immaculate Totem",
        "token_cost": 99,
        "notes": None,
    },
    {
        "source_key": "shb-hades-mount",
        "name": "Hades",
        "category": "mount",
        "expansion": "shb",
        "patch": "5.1",
        "source_type": "extreme",
        "source_duty_name": "The Minstrel's Ballad: Hades's Elegy",
        "source_duty_key": "shb-hades",
        "source_text": "The Minstrel's Ballad: Hades's Elegy",
        "token_name": "Hades Totem",
        "token_cost": 99,
        "notes": None,
    },
    {
        "source_key": "shb-wol-mount",
        "name": "Warrior of Light",
        "category": "mount",
        "expansion": "shb",
        "patch": "5.3",
        "source_type": "extreme",
        "source_duty_name": "The Seat of Sacrifice (Extreme)",
        "source_duty_key": "shb-warrior-of-light",
        "source_text": "The Seat of Sacrifice (Extreme) — Warrior of Light",
        "token_name": "Warrior of Light Totem",
        "token_cost": 99,
        "notes": None,
    },
    {
        "source_key": "shb-emerald-mount",
        "name": "Emerald Gwiber",
        "category": "mount",
        "expansion": "shb",
        "patch": "5.4",
        "source_type": "extreme",
        "source_duty_name": "Castrum Marinum (Extreme)",
        "source_duty_key": "shb-emerald",
        "source_text": "Castrum Marinum (Extreme) — Emerald Weapon",
        "token_name": "Emerald Totem",
        "token_cost": 99,
        "notes": None,
    },
    {
        "source_key": "shb-diamond-mount",
        "name": "Diamond Gwiber",
        "category": "mount",
        "expansion": "shb",
        "patch": "5.5",
        "source_type": "extreme",
        "source_duty_name": "The Cloud Deck (Extreme)",
        "source_duty_key": "shb-diamond",
        "source_text": "The Cloud Deck (Extreme) — Diamond Weapon",
        "token_name": "Diamond Totem",
        "token_cost": 99,
        "notes": None,
    },
]

SHADOWBRINGERS_ULTIMATE_WEAPONS: list[CuratedItem] = [
    {
        "source_key": "shb-ult-tea",
        "name": "Ultimate Alexander Weapons",
        "category": "weapon",
        "expansion": "shb",
        "patch": "5.11",
        "source_type": "ultimate",
        "source_duty_name": "The Epic of Alexander (Ultimate)",
        "source_duty_key": "ult-tea",
        "source_text": "The Epic of Alexander (Ultimate) — The Almighty Alexander",
        "token_name": "Colossus Totem",
        "token_cost": 1,
        "notes": None,
    },
]

# ── Stormblood (4.x) ──────────────────────────────────────────────────────────

STORMBLOOD_EXTREME_MOUNTS: list[CuratedItem] = [
    {
        "source_key": "sb-susano-mount",
        "name": "Reveling Kamuy",
        "category": "mount",
        "expansion": "sb",
        "patch": "4.0",
        "source_type": "extreme",
        "source_duty_name": "The Pool of Tribute (Extreme)",
        "source_duty_key": "sb-susano",
        "source_text": "The Pool of Tribute (Extreme) — Susano",
        "token_name": "Susano Totem",
        "token_cost": 99,
        "notes": None,
    },
    {
        "source_key": "sb-lakshmi-mount",
        "name": "Blissful Kamuy",
        "category": "mount",
        "expansion": "sb",
        "patch": "4.0",
        "source_type": "extreme",
        "source_duty_name": "Emanation (Extreme)",
        "source_duty_key": "sb-lakshmi",
        "source_text": "Emanation (Extreme) — Lakshmi",
        "token_name": "Lakshmi Totem",
        "token_cost": 99,
        "notes": None,
    },
    {
        "source_key": "sb-shinryu-mount",
        "name": "Shinryu",
        "category": "mount",
        "expansion": "sb",
        "patch": "4.1",
        "source_type": "extreme",
        "source_duty_name": "The Minstrel's Ballad: Shinryu's Domain",
        "source_duty_key": "sb-shinryu",
        "source_text": "The Minstrel's Ballad: Shinryu's Domain",
        "token_name": "Shinryu Totem",
        "token_cost": 99,
        "notes": None,
    },
    {
        "source_key": "sb-byakko-mount",
        "name": "Auspicious Kamuy",
        "category": "mount",
        "expansion": "sb",
        "patch": "4.2",
        "source_type": "extreme",
        "source_duty_name": "The Jade Stoa (Extreme)",
        "source_duty_key": "sb-byakko",
        "source_text": "The Jade Stoa (Extreme) — Byakko",
        "token_name": "Byakko Totem",
        "token_cost": 99,
        "notes": None,
    },
    {
        "source_key": "sb-tsukuyomi-mount",
        "name": "Lunar Kamuy",
        "category": "mount",
        "expansion": "sb",
        "patch": "4.3",
        "source_type": "extreme",
        "source_duty_name": "The Minstrel's Ballad: Tsukuyomi's Pain",
        "source_duty_key": "sb-tsukuyomi",
        "source_text": "The Minstrel's Ballad: Tsukuyomi's Pain",
        "token_name": "Tsukuyomi Totem",
        "token_cost": 99,
        "notes": None,
    },
    {
        "source_key": "sb-suzaku-mount",
        "name": "Euphonious Kamuy",
        "category": "mount",
        "expansion": "sb",
        "patch": "4.4",
        "source_type": "extreme",
        "source_duty_name": "Hells' Kier (Extreme)",
        "source_duty_key": "sb-suzaku",
        "source_text": "Hells' Kier (Extreme) — Suzaku",
        "token_name": "Suzaku Totem",
        "token_cost": 99,
        "notes": None,
    },
    {
        "source_key": "sb-seiryu-mount",
        "name": "Legendary Kamuy",
        "category": "mount",
        "expansion": "sb",
        "patch": "4.5",
        "source_type": "extreme",
        "source_duty_name": "The Wreath of Snakes (Extreme)",
        "source_duty_key": "sb-seiryu",
        "source_text": "The Wreath of Snakes (Extreme) — Seiryu",
        "token_name": "Seiryu Totem",
        "token_cost": 99,
        "notes": None,
    },
]

STORMBLOOD_ULTIMATE_WEAPONS: list[CuratedItem] = [
    {
        "source_key": "sb-ult-ucob",
        "name": "Ultimate Dreadwyrm Weapons",
        "category": "weapon",
        "expansion": "sb",
        "patch": "4.11",
        "source_type": "ultimate",
        "source_duty_name": "The Unending Coil of Bahamut (Ultimate)",
        "source_duty_key": "ult-ucob",
        "source_text": "The Unending Coil of Bahamut (Ultimate) — Bahamut Prime",
        "token_name": "Dreadwyrm Totem",
        "token_cost": 1,
        "notes": None,
    },
    {
        "source_key": "sb-ult-uwu",
        "name": "Ultima Weapons",
        "category": "weapon",
        "expansion": "sb",
        "patch": "4.31",
        "source_type": "ultimate",
        "source_duty_name": "The Weapon's Refrain (Ultimate)",
        "source_duty_key": "ult-uwu",
        "source_text": "The Weapon's Refrain (Ultimate) — The Ultima Weapon",
        "token_name": "Ultima Totem",
        "token_cost": 1,
        "notes": None,
    },
]

# ── Heavensward (3.x) ─────────────────────────────────────────────────────────

HEAVENSWARD_EXTREME_MOUNTS: list[CuratedItem] = [
    {
        "source_key": "hw-bismarck-mount",
        "name": "White Lanner",
        "category": "mount",
        "expansion": "hw",
        "patch": "3.0",
        "source_type": "extreme",
        "source_duty_name": "The Limitless Blue (Extreme)",
        "source_duty_key": "hw-bismarck",
        "source_text": "The Limitless Blue (Extreme) — Bismarck",
        "token_name": "Bismarck Totem",
        "token_cost": 99,
        "notes": None,
    },
    {
        "source_key": "hw-ravana-mount",
        "name": "Rose Lanner",
        "category": "mount",
        "expansion": "hw",
        "patch": "3.0",
        "source_type": "extreme",
        "source_duty_name": "Thok ast Thok (Extreme)",
        "source_duty_key": "hw-ravana",
        "source_text": "Thok ast Thok (Extreme) — Ravana",
        "token_name": "Ravana Totem",
        "token_cost": 99,
        "notes": None,
    },
    {
        "source_key": "hw-thordan-mount",
        "name": "Round Lanner",
        "category": "mount",
        "expansion": "hw",
        "patch": "3.1",
        "source_type": "extreme",
        "source_duty_name": "The Minstrel's Ballad: Thordan's Reign",
        "source_duty_key": "hw-thordan",
        "source_text": "The Minstrel's Ballad: Thordan's Reign",
        "token_name": "Thordan Totem",
        "token_cost": 99,
        "notes": None,
    },
    {
        "source_key": "hw-sephirot-mount",
        "name": "Warring Lanner",
        "category": "mount",
        "expansion": "hw",
        "patch": "3.2",
        "source_type": "extreme",
        "source_duty_name": "Containment Bay S1T7 (Extreme)",
        "source_duty_key": "hw-sephirot",
        "source_text": "Containment Bay S1T7 (Extreme) — Sephirot",
        "token_name": "Sephirot Totem",
        "token_cost": 99,
        "notes": None,
    },
    {
        "source_key": "hw-nidhogg-mount",
        "name": "Dark Lanner",
        "category": "mount",
        "expansion": "hw",
        "patch": "3.3",
        "source_type": "extreme",
        "source_duty_name": "The Minstrel's Ballad: Nidhogg's Rage",
        "source_duty_key": "hw-nidhogg",
        "source_text": "The Minstrel's Ballad: Nidhogg's Rage",
        "token_name": "Nidhogg Totem",
        "token_cost": 99,
        "notes": None,
    },
    {
        "source_key": "hw-sophia-mount",
        "name": "Sophia Lanner",
        "category": "mount",
        "expansion": "hw",
        "patch": "3.4",
        "source_type": "extreme",
        "source_duty_name": "Containment Bay P1T6 (Extreme)",
        "source_duty_key": "hw-sophia",
        "source_text": "Containment Bay P1T6 (Extreme) — Sophia",
        "token_name": "Sophia Totem",
        "token_cost": 99,
        "notes": None,
    },
    {
        "source_key": "hw-zurvan-mount",
        "name": "Demonic Lanner",
        "category": "mount",
        "expansion": "hw",
        "patch": "3.5",
        "source_type": "extreme",
        "source_duty_name": "Containment Bay Z1T9 (Extreme)",
        "source_duty_key": "hw-zurvan",
        "source_text": "Containment Bay Z1T9 (Extreme) — Zurvan",
        "token_name": "Zurvan Totem",
        "token_cost": 99,
        "notes": None,
    },
]

# ── A Realm Reborn (2.x) ──────────────────────────────────────────────────────

ARR_EXTREME_MOUNTS: list[CuratedItem] = [
    {
        "source_key": "arr-garuda-mount",
        "name": "Xanthos",
        "category": "mount",
        "expansion": "arr",
        "patch": "2.0",
        "source_type": "extreme",
        "source_duty_name": "The Howling Eye (Extreme)",
        "source_duty_key": "arr-garuda",
        "source_text": "The Howling Eye (Extreme) — Garuda",
        "token_name": "Garuda Totem",
        "token_cost": 99,
        "notes": None,
    },
    {
        "source_key": "arr-titan-mount",
        "name": "Gullfaxi",
        "category": "mount",
        "expansion": "arr",
        "patch": "2.0",
        "source_type": "extreme",
        "source_duty_name": "The Navel (Extreme)",
        "source_duty_key": "arr-titan",
        "source_text": "The Navel (Extreme) — Titan",
        "token_name": "Titan Totem",
        "token_cost": 99,
        "notes": None,
    },
    {
        "source_key": "arr-ifrit-mount",
        "name": "Aithon",
        "category": "mount",
        "expansion": "arr",
        "patch": "2.0",
        "source_type": "extreme",
        "source_duty_name": "The Bowl of Embers (Extreme)",
        "source_duty_key": "arr-ifrit",
        "source_text": "The Bowl of Embers (Extreme) — Ifrit",
        "token_name": "Ifrit Totem",
        "token_cost": 99,
        "notes": None,
    },
    {
        "source_key": "arr-leviathan-mount",
        "name": "Enbarr",
        "category": "mount",
        "expansion": "arr",
        "patch": "2.2",
        "source_type": "extreme",
        "source_duty_name": "The Whorleater (Extreme)",
        "source_duty_key": "arr-leviathan",
        "source_text": "The Whorleater (Extreme) — Leviathan",
        "token_name": "Leviathan Totem",
        "token_cost": 99,
        "notes": None,
    },
    {
        "source_key": "arr-ramuh-mount",
        "name": "Markab",
        "category": "mount",
        "expansion": "arr",
        "patch": "2.3",
        "source_type": "extreme",
        "source_duty_name": "The Striking Tree (Extreme)",
        "source_duty_key": "arr-ramuh",
        "source_text": "The Striking Tree (Extreme) — Ramuh",
        "token_name": "Ramuh Totem",
        "token_cost": 99,
        "notes": None,
    },
    {
        "source_key": "arr-shiva-mount",
        "name": "Boreas",
        "category": "mount",
        "expansion": "arr",
        "patch": "2.4",
        "source_type": "extreme",
        "source_duty_name": "Akh Afah Amphitheatre (Extreme)",
        "source_duty_key": "arr-shiva",
        "source_text": "Akh Afah Amphitheatre (Extreme) — Shiva",
        "token_name": "Shiva Totem",
        "token_cost": 99,
        "notes": None,
    },
]

# ── Assembled catalog ──────────────────────────────────────────────────────────

ALL_CURATED_ITEMS: list[CuratedItem] = [
    *DAWNTRAIL_EXTREME_MOUNTS,
    *DAWNTRAIL_ULTIMATE_WEAPONS,
    *ENDWALKER_EXTREME_MOUNTS,
    *ENDWALKER_ULTIMATE_WEAPONS,
    *SHADOWBRINGERS_EXTREME_MOUNTS,
    *SHADOWBRINGERS_ULTIMATE_WEAPONS,
    *STORMBLOOD_EXTREME_MOUNTS,
    *STORMBLOOD_ULTIMATE_WEAPONS,
    *HEAVENSWARD_EXTREME_MOUNTS,
    *ARR_EXTREME_MOUNTS,
]
