"""initial_schema

Revision ID: c94640ed9426
Revises:
Create Date: 2025-12-29 05:23:50.603270

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c94640ed9426"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("discord_id", sa.String(length=20), nullable=False),
        sa.Column("discord_username", sa.String(length=100), nullable=False),
        sa.Column("discord_discriminator", sa.String(length=10), nullable=True),
        sa.Column("discord_avatar", sa.String(length=255), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("display_name", sa.String(length=100), nullable=True),
        sa.Column("created_at", sa.Text(), nullable=False),
        sa.Column("updated_at", sa.Text(), nullable=False),
        sa.Column("last_login_at", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_discord_id"), ["discord_id"], unique=True)

    op.create_table(
        "static_groups",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("owner_id", sa.String(length=36), nullable=False),
        sa.Column("share_code", sa.String(length=6), nullable=False),
        sa.Column("is_public", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.Text(), nullable=False),
        sa.Column("updated_at", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("static_groups", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_static_groups_owner_id"), ["owner_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_static_groups_share_code"), ["share_code"], unique=True
        )

    op.create_table(
        "invitations",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("static_group_id", sa.String(length=36), nullable=False),
        sa.Column("created_by_id", sa.String(length=36), nullable=False),
        sa.Column("invite_code", sa.String(length=12), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("expires_at", sa.Text(), nullable=True),
        sa.Column("max_uses", sa.Integer(), nullable=True),
        sa.Column("use_count", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.Text(), nullable=False),
        sa.Column("updated_at", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(["static_group_id"], ["static_groups.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("invitations", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_invitations_created_by_id"), ["created_by_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_invitations_invite_code"), ["invite_code"], unique=True
        )
        batch_op.create_index(
            batch_op.f("ix_invitations_static_group_id"), ["static_group_id"], unique=False
        )

    op.create_table(
        "memberships",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("static_group_id", sa.String(length=36), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("joined_at", sa.Text(), nullable=False),
        sa.Column("updated_at", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["static_group_id"],
            ["static_groups.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "static_group_id", name="uq_user_static_group"),
    )
    with op.batch_alter_table("memberships", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_memberships_static_group_id"), ["static_group_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_memberships_user_id"), ["user_id"], unique=False)

    op.create_table(
        "tier_snapshots",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("static_group_id", sa.String(length=36), nullable=False),
        sa.Column("tier_id", sa.String(length=50), nullable=False),
        sa.Column("content_type", sa.String(length=20), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.Text(), nullable=False),
        sa.Column("updated_at", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(["static_group_id"], ["static_groups.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("static_group_id", "tier_id", name="uq_group_tier"),
    )
    with op.batch_alter_table("tier_snapshots", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_tier_snapshots_static_group_id"), ["static_group_id"], unique=False
        )

    op.create_table(
        "snapshot_players",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tier_snapshot_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=True),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("job", sa.String(length=10), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("position", sa.String(length=5), nullable=True),
        sa.Column("tank_role", sa.String(length=5), nullable=True),
        sa.Column("template_role", sa.String(length=20), nullable=True),
        sa.Column("configured", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("is_substitute", sa.Boolean(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("lodestone_id", sa.String(length=50), nullable=True),
        sa.Column("bis_link", sa.Text(), nullable=True),
        sa.Column("fflogs_id", sa.Integer(), nullable=True),
        sa.Column("last_sync", sa.Text(), nullable=True),
        sa.Column("gear", sa.JSON(), nullable=False),
        sa.Column("tome_weapon", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.Text(), nullable=False),
        sa.Column("updated_at", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(["tier_snapshot_id"], ["tier_snapshots.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("snapshot_players", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_snapshot_players_tier_snapshot_id"), ["tier_snapshot_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_snapshot_players_user_id"), ["user_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("snapshot_players", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_snapshot_players_user_id"))
        batch_op.drop_index(batch_op.f("ix_snapshot_players_tier_snapshot_id"))

    op.drop_table("snapshot_players")
    with op.batch_alter_table("tier_snapshots", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_tier_snapshots_static_group_id"))

    op.drop_table("tier_snapshots")
    with op.batch_alter_table("memberships", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_memberships_user_id"))
        batch_op.drop_index(batch_op.f("ix_memberships_static_group_id"))

    op.drop_table("memberships")
    with op.batch_alter_table("invitations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_invitations_static_group_id"))
        batch_op.drop_index(batch_op.f("ix_invitations_invite_code"))
        batch_op.drop_index(batch_op.f("ix_invitations_created_by_id"))

    op.drop_table("invitations")
    with op.batch_alter_table("static_groups", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_static_groups_share_code"))
        batch_op.drop_index(batch_op.f("ix_static_groups_owner_id"))

    op.drop_table("static_groups")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_discord_id"))

    op.drop_table("users")
    # ### end Alembic commands ###
