"""Pydantic schemas"""

from .invitation import (
    InvitationAcceptResponse,
    InvitationCreate,
    InvitationPreview,
    InvitationResponse,
)
from .loot_tracking import (
    LootLogEntryCreate,
    LootLogEntryResponse,
    LootLogEntryUpdate,
    LootMethodEnum,
    MarkFloorClearedRequest,
    MaterialBalanceResponse,
    MaterialLogEntryCreate,
    MaterialLogEntryResponse,
    MaterialLogEntryUpdate,
    MaterialTypeEnum,
    PageBalanceResponse,
    PageLedgerEntryCreate,
    PageLedgerEntryResponse,
    TransactionTypeEnum,
    WeekOperationResponse,
)
from .static_group import (
    AdminStaticGroupListItem,
    AdminStaticGroupListResponse,
    AdvancedPriorityOptions,
    DuplicateGroupRequest,
    GroupSourceEnum,
    InteractedUserInfo,
    JobBasedConfig,
    JobPriorityConfig,
    MemberInfo,
    MemberRoleEnum,
    MembershipCreate,
    MembershipResponse,
    MembershipUpdate,
    OwnerInfo,
    PlayerBasedConfig,
    PlayerPriorityConfig,
    PriorityGroupConfig,
    RoleBasedConfig,
    StaticGroupCreate,
    StaticGroupListItem,
    StaticGroupResponse,
    StaticGroupUpdate,
    StaticGroupWithMembers,
    StaticPrioritySettings,
    StaticSettingsSchema,
)
from .weekly_assignment import (
    WeeklyAssignmentBulkCreate,
    WeeklyAssignmentBulkDelete,
    WeeklyAssignmentCreate,
    WeeklyAssignmentResponse,
    WeeklyAssignmentUpdate,
)
from .tier_snapshot import (
    AssignPlayerRequest,
    GearSlotStatus,
    LinkedPlayerInfo,
    LinkedUserInfo,
    RolloverRequest,
    RolloverResponse,
    SnapshotPlayerCreate,
    SnapshotPlayerResponse,
    SnapshotPlayerUpdate,
    TierSnapshotCreate,
    TierSnapshotResponse,
    TierSnapshotUpdate,
    TierSnapshotWithPlayers,
    TomeWeaponStatus,
    WeaponPrioritiesUpdate,
    WeaponPriority,
    WeaponPrioritySettingsUpdate,
)
from .user import (
    DiscordAuthUrl,
    DiscordCallback,
    RefreshTokenRequest,
    TokenResponse,
    UserResponse,
    UserUpdate,
)

__all__ = [
    # Gear Status (from tier_snapshot)
    "GearSlotStatus",
    "LinkedPlayerInfo",
    "LinkedUserInfo",
    "TomeWeaponStatus",
    # Invitation
    "InvitationAcceptResponse",
    "InvitationCreate",
    "InvitationPreview",
    "InvitationResponse",
    # Loot Tracking
    "LootLogEntryCreate",
    "LootLogEntryResponse",
    "LootLogEntryUpdate",
    "LootMethodEnum",
    "MarkFloorClearedRequest",
    "MaterialBalanceResponse",
    "MaterialLogEntryCreate",
    "MaterialLogEntryResponse",
    "MaterialLogEntryUpdate",
    "MaterialTypeEnum",
    "PageBalanceResponse",
    "PageLedgerEntryCreate",
    "PageLedgerEntryResponse",
    "TransactionTypeEnum",
    "WeekOperationResponse",
    # Static Group
    "AdminStaticGroupListItem",
    "AdminStaticGroupListResponse",
    "AdvancedPriorityOptions",
    "DuplicateGroupRequest",
    "GroupSourceEnum",
    "InteractedUserInfo",
    "JobBasedConfig",
    "JobPriorityConfig",
    "MemberInfo",
    "MemberRoleEnum",
    "MembershipCreate",
    "MembershipResponse",
    "MembershipUpdate",
    "OwnerInfo",
    "PlayerBasedConfig",
    "PlayerPriorityConfig",
    "PriorityGroupConfig",
    "RoleBasedConfig",
    "StaticGroupCreate",
    "StaticGroupListItem",
    "StaticGroupResponse",
    "StaticGroupUpdate",
    "StaticGroupWithMembers",
    "StaticPrioritySettings",
    "StaticSettingsSchema",
    # Tier Snapshot
    "AssignPlayerRequest",
    "RolloverRequest",
    "RolloverResponse",
    "SnapshotPlayerCreate",
    "SnapshotPlayerResponse",
    "SnapshotPlayerUpdate",
    "TierSnapshotCreate",
    "TierSnapshotResponse",
    "TierSnapshotUpdate",
    "TierSnapshotWithPlayers",
    "WeaponPrioritiesUpdate",
    "WeaponPriority",
    "WeaponPrioritySettingsUpdate",
    # Weekly Assignment
    "WeeklyAssignmentBulkCreate",
    "WeeklyAssignmentBulkDelete",
    "WeeklyAssignmentCreate",
    "WeeklyAssignmentResponse",
    "WeeklyAssignmentUpdate",
    # User/Auth
    "DiscordAuthUrl",
    "DiscordCallback",
    "RefreshTokenRequest",
    "TokenResponse",
    "UserResponse",
    "UserUpdate",
]
