"""Pydantic schemas"""

from .analytics import (
    AnalyticsEventBatch,
    AnalyticsEventIn,
    ErrorDetailItem,
    ErrorGroupDetailResponse,
    ErrorGroupItem,
    ErrorGroupListResponse,
    ErrorReportIn,
    GrowthPoint,
    GrowthResponse,
    OverviewResponse,
    TopStaticItem,
    TopUserItem,
    UsageEventItem,
    UsageResponse,
)
from .api_key import (
    ApiKeyCreate,
    ApiKeyCreateResponse,
    ApiKeyResponse,
)
from .invitation import (
    InvitationAcceptResponse,
    InvitationCreate,
    InvitationPreview,
    InvitationResponse,
)
from .join_request import (
    JoinRequestCreate,
    JoinRequestListResponse,
    JoinRequestResponse,
    JoinRequestStatusEnum,
    RequesterInfo,
)
from .schedule import (
    AvailabilityDateSummary,
    AvailabilitySubmit,
    RsvpCreate,
    RsvpResponse,
    RsvpStatusEnum,
    ScheduleSessionCreate,
    ScheduleSessionResponse,
    ScheduleSessionUpdate,
    UserAvailabilityResponse,
)
from .loot_tracking import (
    LootLogEntryCreate,
    LootLogEntryResponse,
    LootLogEntryUpdate,
    LootMethodEnum,
    MarkFloorClearedRequest,
    MaterialBalanceResponse,
    MaterialLogEntryCreate,
    MaterialLogEntryResponse,
    MaterialLogEntryUpdate,
    MaterialTypeEnum,
    PageBalanceResponse,
    PageLedgerEntryCreate,
    PageLedgerEntryResponse,
    TransactionTypeEnum,
    WeekOperationResponse,
)
from .static_group import (
    AdminStaticGroupListItem,
    AdminStaticGroupListResponse,
    AdvancedPriorityOptions,
    DuplicateGroupRequest,
    GroupSourceEnum,
    InteractedUserInfo,
    JobBasedConfig,
    JobPriorityConfig,
    MemberInfo,
    MemberRoleEnum,
    MembershipCreate,
    MembershipResponse,
    MembershipUpdate,
    OwnerInfo,
    PlayerBasedConfig,
    PlayerPriorityConfig,
    PriorityGroupConfig,
    RoleBasedConfig,
    StaticGroupCreate,
    StaticGroupListItem,
    StaticGroupResponse,
    StaticGroupUpdate,
    StaticGroupWithMembers,
    StaticPrioritySettings,
    StaticSettingsSchema,
)
from .weekly_assignment import (
    WeeklyAssignmentBulkCreate,
    WeeklyAssignmentBulkDelete,
    WeeklyAssignmentBulkItem,
    WeeklyAssignmentCreate,
    WeeklyAssignmentResponse,
    WeeklyAssignmentUpdate,
)
from .tier_snapshot import (
    AssignPlayerRequest,
    GearSlotStatus,
    LinkedPlayerInfo,
    LinkedUserInfo,
    RolloverRequest,
    RolloverResponse,
    SnapshotPlayerCreate,
    SnapshotPlayerResponse,
    SnapshotPlayerUpdate,
    TierSnapshotCreate,
    TierSnapshotResponse,
    TierSnapshotUpdate,
    TierSnapshotWithPlayers,
    TomeWeaponStatus,
    WeaponPrioritiesUpdate,
    WeaponPriority,
    WeaponPrioritySettingsUpdate,
)
from .user import (
    DiscordAuthUrl,
    DiscordCallback,
    RefreshTokenRequest,
    TokenResponse,
    UserResponse,
    UserUpdate,
)

__all__ = [
    # Analytics
    "AnalyticsEventBatch",
    "AnalyticsEventIn",
    "ErrorDetailItem",
    "ErrorGroupDetailResponse",
    "ErrorGroupItem",
    "ErrorGroupListResponse",
    "ErrorReportIn",
    "GrowthPoint",
    "GrowthResponse",
    "OverviewResponse",
    "TopStaticItem",
    "TopUserItem",
    "UsageEventItem",
    "UsageResponse",
    # API Key
    "ApiKeyCreate",
    "ApiKeyCreateResponse",
    "ApiKeyResponse",
    # Gear Status (from tier_snapshot)
    "GearSlotStatus",
    "LinkedPlayerInfo",
    "LinkedUserInfo",
    "TomeWeaponStatus",
    # Invitation
    "InvitationAcceptResponse",
    "InvitationCreate",
    "InvitationPreview",
    "InvitationResponse",
    # Join Request
    "JoinRequestCreate",
    "JoinRequestListResponse",
    "JoinRequestResponse",
    "JoinRequestStatusEnum",
    "RequesterInfo",
    # Schedule & Availability
    "AvailabilityDateSummary",
    "AvailabilitySubmit",
    "RsvpCreate",
    "RsvpResponse",
    "RsvpStatusEnum",
    "ScheduleSessionCreate",
    "ScheduleSessionResponse",
    "ScheduleSessionUpdate",
    "UserAvailabilityResponse",
    # Loot Tracking
    "LootLogEntryCreate",
    "LootLogEntryResponse",
    "LootLogEntryUpdate",
    "LootMethodEnum",
    "MarkFloorClearedRequest",
    "MaterialBalanceResponse",
    "MaterialLogEntryCreate",
    "MaterialLogEntryResponse",
    "MaterialLogEntryUpdate",
    "MaterialTypeEnum",
    "PageBalanceResponse",
    "PageLedgerEntryCreate",
    "PageLedgerEntryResponse",
    "TransactionTypeEnum",
    "WeekOperationResponse",
    # Static Group
    "AdminStaticGroupListItem",
    "AdminStaticGroupListResponse",
    "AdvancedPriorityOptions",
    "DuplicateGroupRequest",
    "GroupSourceEnum",
    "InteractedUserInfo",
    "JobBasedConfig",
    "JobPriorityConfig",
    "MemberInfo",
    "MemberRoleEnum",
    "MembershipCreate",
    "MembershipResponse",
    "MembershipUpdate",
    "OwnerInfo",
    "PlayerBasedConfig",
    "PlayerPriorityConfig",
    "PriorityGroupConfig",
    "RoleBasedConfig",
    "StaticGroupCreate",
    "StaticGroupListItem",
    "StaticGroupResponse",
    "StaticGroupUpdate",
    "StaticGroupWithMembers",
    "StaticPrioritySettings",
    "StaticSettingsSchema",
    # Tier Snapshot
    "AssignPlayerRequest",
    "RolloverRequest",
    "RolloverResponse",
    "SnapshotPlayerCreate",
    "SnapshotPlayerResponse",
    "SnapshotPlayerUpdate",
    "TierSnapshotCreate",
    "TierSnapshotResponse",
    "TierSnapshotUpdate",
    "TierSnapshotWithPlayers",
    "WeaponPrioritiesUpdate",
    "WeaponPriority",
    "WeaponPrioritySettingsUpdate",
    # Weekly Assignment
    "WeeklyAssignmentBulkCreate",
    "WeeklyAssignmentBulkDelete",
    "WeeklyAssignmentBulkItem",
    "WeeklyAssignmentCreate",
    "WeeklyAssignmentResponse",
    "WeeklyAssignmentUpdate",
    # User/Auth
    "DiscordAuthUrl",
    "DiscordCallback",
    "RefreshTokenRequest",
    "TokenResponse",
    "UserResponse",
    "UserUpdate",
]
