import { describe, it, expect } from 'vitest';
import {
  stripAIAttributions,
  AI_ATTRIBUTION_PATTERNS,
  DISCORD_TITLE_LIMIT,
  DISCORD_DESCRIPTION_LIMIT,
  TRUNCATION_MESSAGE_RESERVE,
} from './discord-changelog.js';

describe('discord-changelog', () => {
  describe('stripAIAttributions', () => {
    it('removes Claude co-author lines', () => {
      const input = `feat: add feature

Some description

Co-Authored-By: Claude <noreply@anthropic.com>`;
      const result = stripAIAttributions(input);
      expect(result).toBe('feat: add feature\n\nSome description');
    });

    it('removes Anthropic domain co-author lines', () => {
      const input = `fix: bug fix

Co-Authored-By: AI Assistant <assistant@anthropic.com>`;
      const result = stripAIAttributions(input);
      expect(result).toBe('fix: bug fix');
    });

    it('removes GitHub Copilot co-author lines', () => {
      const input = `refactor: cleanup

Co-Authored-By: GitHub Copilot`;
      const result = stripAIAttributions(input);
      expect(result).toBe('refactor: cleanup');
    });

    it('removes "Generated with Claude Code" lines', () => {
      const input = `docs: update readme

Generated with Claude Code`;
      const result = stripAIAttributions(input);
      expect(result).toBe('docs: update readme');
    });

    it('removes "Generated by Claude" lines', () => {
      const input = `test: add tests

Generated by Claude`;
      const result = stripAIAttributions(input);
      expect(result).toBe('test: add tests');
    });

    it('removes emoji-prefixed Claude Code attribution', () => {
      const input = `feat: new feature

\ud83e\udd16 Generated with [Claude Code]`;
      const result = stripAIAttributions(input);
      expect(result).toBe('feat: new feature');
    });

    it('removes "Generated with Cursor" lines', () => {
      const input = `style: format code

Generated with Cursor`;
      const result = stripAIAttributions(input);
      expect(result).toBe('style: format code');
    });

    it('removes "Generated by Copilot" lines', () => {
      const input = `chore: update deps

Generated by Copilot`;
      const result = stripAIAttributions(input);
      expect(result).toBe('chore: update deps');
    });

    it('removes multiple AI attributions in one message', () => {
      const input = `feat: complex feature

This is a detailed description.

Co-Authored-By: Claude <noreply@anthropic.com>
Generated with Claude Code`;
      const result = stripAIAttributions(input);
      expect(result).toBe('feat: complex feature\n\nThis is a detailed description.');
    });

    it('collapses multiple consecutive blank lines', () => {
      const input = `feat: feature



Multiple blank lines above`;
      const result = stripAIAttributions(input);
      expect(result).toBe('feat: feature\n\nMultiple blank lines above');
    });

    it('handles messages with no AI attributions', () => {
      const input = `feat: regular commit

This has no AI attribution.`;
      const result = stripAIAttributions(input);
      expect(result).toBe('feat: regular commit\n\nThis has no AI attribution.');
    });

    it('handles empty messages', () => {
      const result = stripAIAttributions('');
      expect(result).toBe('');
    });

    it('handles messages that are only AI attribution', () => {
      const input = 'Co-Authored-By: Claude <noreply@anthropic.com>';
      const result = stripAIAttributions(input);
      expect(result).toBe('');
    });

    it('is case insensitive for pattern matching', () => {
      const input = `feat: feature

CO-AUTHORED-BY: CLAUDE <noreply@ANTHROPIC.COM>`;
      const result = stripAIAttributions(input);
      expect(result).toBe('feat: feature');
    });

    it('preserves legitimate co-authors without AI keywords', () => {
      const input = `feat: collaborative feature

Co-Authored-By: John Smith <john@example.com>`;
      const result = stripAIAttributions(input);
      expect(result).toBe('feat: collaborative feature\n\nCo-Authored-By: John Smith <john@example.com>');
    });
  });

  describe('constants', () => {
    it('DISCORD_TITLE_LIMIT is 256', () => {
      expect(DISCORD_TITLE_LIMIT).toBe(256);
    });

    it('DISCORD_DESCRIPTION_LIMIT is 4000', () => {
      expect(DISCORD_DESCRIPTION_LIMIT).toBe(4000);
    });

    it('TRUNCATION_MESSAGE_RESERVE is 80', () => {
      expect(TRUNCATION_MESSAGE_RESERVE).toBe(80);
    });

    it('has 7 AI attribution patterns', () => {
      expect(AI_ATTRIBUTION_PATTERNS).toHaveLength(7);
    });
  });
});
