import { describe, it, expect } from 'vitest';
import { existsSync } from 'fs';
import {
  stripAIAttributions,
  parseReleaseNotes,
  buildCommitEmbed,
  buildReleaseEmbed,
  AI_ATTRIBUTION_PATTERNS,
  DISCORD_TITLE_LIMIT,
  DISCORD_DESCRIPTION_LIMIT,
  TRUNCATION_MESSAGE_RESERVE,
  RELEASE_NOTES_PATH,
} from './discord-changelog.js';

describe('discord-changelog', () => {
  describe('stripAIAttributions', () => {
    it('removes Claude co-author lines', () => {
      const input = `feat: add feature

Some description

Co-Authored-By: Claude <noreply@anthropic.com>`;
      const result = stripAIAttributions(input);
      expect(result).toBe('feat: add feature\n\nSome description');
    });

    it('removes Anthropic domain co-author lines', () => {
      const input = `fix: bug fix

Co-Authored-By: AI Assistant <assistant@anthropic.com>`;
      const result = stripAIAttributions(input);
      expect(result).toBe('fix: bug fix');
    });

    it('removes GitHub Copilot co-author lines', () => {
      const input = `refactor: cleanup

Co-Authored-By: GitHub Copilot`;
      const result = stripAIAttributions(input);
      expect(result).toBe('refactor: cleanup');
    });

    it('removes "Generated with Claude Code" lines', () => {
      const input = `docs: update readme

Generated with Claude Code`;
      const result = stripAIAttributions(input);
      expect(result).toBe('docs: update readme');
    });

    it('removes "Generated by Claude" lines', () => {
      const input = `test: add tests

Generated by Claude`;
      const result = stripAIAttributions(input);
      expect(result).toBe('test: add tests');
    });

    it('removes emoji-prefixed Claude Code attribution', () => {
      const input = `feat: new feature

\ud83e\udd16 Generated with [Claude Code]`;
      const result = stripAIAttributions(input);
      expect(result).toBe('feat: new feature');
    });

    it('removes "Generated with Cursor" lines', () => {
      const input = `style: format code

Generated with Cursor`;
      const result = stripAIAttributions(input);
      expect(result).toBe('style: format code');
    });

    it('removes "Generated by Copilot" lines', () => {
      const input = `chore: update deps

Generated by Copilot`;
      const result = stripAIAttributions(input);
      expect(result).toBe('chore: update deps');
    });

    it('removes multiple AI attributions in one message', () => {
      const input = `feat: complex feature

This is a detailed description.

Co-Authored-By: Claude <noreply@anthropic.com>
Generated with Claude Code`;
      const result = stripAIAttributions(input);
      expect(result).toBe('feat: complex feature\n\nThis is a detailed description.');
    });

    it('collapses multiple consecutive blank lines', () => {
      const input = `feat: feature



Multiple blank lines above`;
      const result = stripAIAttributions(input);
      expect(result).toBe('feat: feature\n\nMultiple blank lines above');
    });

    it('handles messages with no AI attributions', () => {
      const input = `feat: regular commit

This has no AI attribution.`;
      const result = stripAIAttributions(input);
      expect(result).toBe('feat: regular commit\n\nThis has no AI attribution.');
    });

    it('handles empty messages', () => {
      const result = stripAIAttributions('');
      expect(result).toBe('');
    });

    it('handles messages that are only AI attribution', () => {
      const input = 'Co-Authored-By: Claude <noreply@anthropic.com>';
      const result = stripAIAttributions(input);
      expect(result).toBe('');
    });

    it('is case insensitive for pattern matching', () => {
      const input = `feat: feature

CO-AUTHORED-BY: CLAUDE <noreply@ANTHROPIC.COM>`;
      const result = stripAIAttributions(input);
      expect(result).toBe('feat: feature');
    });

    it('preserves legitimate co-authors without AI keywords', () => {
      const input = `feat: collaborative feature

Co-Authored-By: John Smith <john@example.com>`;
      const result = stripAIAttributions(input);
      expect(result).toBe('feat: collaborative feature\n\nCo-Authored-By: John Smith <john@example.com>');
    });
  });

  describe('constants', () => {
    it('DISCORD_TITLE_LIMIT is 256', () => {
      expect(DISCORD_TITLE_LIMIT).toBe(256);
    });

    it('DISCORD_DESCRIPTION_LIMIT is 4000', () => {
      expect(DISCORD_DESCRIPTION_LIMIT).toBe(4000);
    });

    it('TRUNCATION_MESSAGE_RESERVE is 80', () => {
      expect(TRUNCATION_MESSAGE_RESERVE).toBe(80);
    });

    it('has 7 AI attribution patterns', () => {
      expect(AI_ATTRIBUTION_PATTERNS).toHaveLength(7);
    });
  });

  describe('parseReleaseNotes', () => {
    it('returns parsed release notes from the actual file', () => {
      // This tests against the actual releaseNotes.ts file
      const result = parseReleaseNotes();

      expect(result).not.toBeNull();
      expect(result.currentVersion).toMatch(/^\d+\.\d+\.\d+$/);
      expect(result.latestRelease).toBeDefined();
      expect(result.latestRelease.version).toMatch(/^\d+\.\d+\.\d+$/);
      expect(result.latestRelease.date).toMatch(/^\d{4}-\d{2}-\d{2}$/);
      expect(Array.isArray(result.latestRelease.highlights)).toBe(true);
    });

    it('RELEASE_NOTES_PATH points to an existing file', () => {
      expect(existsSync(RELEASE_NOTES_PATH)).toBe(true);
    });

    it('currentVersion matches latestRelease.version', () => {
      const result = parseReleaseNotes();
      expect(result.currentVersion).toBe(result.latestRelease.version);
    });
  });

  describe('buildCommitEmbed', () => {
    it('creates embed with title from commit message', () => {
      const embed = buildCommitEmbed('abc1234567890', 'feat: add new feature', 'user/repo');
      const data = embed.toJSON();

      expect(data.title).toBe('feat: add new feature');
      expect(data.url).toBe('https://github.com/user/repo/commit/abc1234567890');
    });

    it('truncates long titles to 256 characters', () => {
      const longTitle = 'a'.repeat(300);
      const embed = buildCommitEmbed('abc1234', longTitle, 'user/repo');
      const data = embed.toJSON();

      expect(data.title.length).toBeLessThanOrEqual(DISCORD_TITLE_LIMIT);
      expect(data.title.endsWith('...')).toBe(true);
    });

    it('uses shortSha as fallback when message is empty', () => {
      const embed = buildCommitEmbed('abc1234567890', '', 'user/repo');
      const data = embed.toJSON();

      expect(data.title).toBe('abc1234');
    });

    it('uses shortSha as fallback when message is only AI attribution', () => {
      const embed = buildCommitEmbed('abc1234567890', 'Co-Authored-By: Claude <noreply@anthropic.com>', 'user/repo');
      const data = embed.toJSON();

      expect(data.title).toBe('abc1234');
    });

    it('includes commit body as description', () => {
      const message = `feat: add feature

This is the commit body with more details.`;
      const embed = buildCommitEmbed('abc1234', message, 'user/repo');
      const data = embed.toJSON();

      expect(data.description).toBe('This is the commit body with more details.');
    });

    it('truncates long descriptions with character count', () => {
      const longBody = 'x'.repeat(5000);
      const message = `feat: title\n\n${longBody}`;
      const embed = buildCommitEmbed('abc1234', message, 'user/repo');
      const data = embed.toJSON();

      expect(data.description.length).toBeLessThanOrEqual(DISCORD_DESCRIPTION_LIMIT);
      expect(data.description).toContain('more characters');
    });

    it('sets footer with short SHA and author', () => {
      const embed = buildCommitEmbed('abc1234567890', 'feat: test', 'user/repo');
      const data = embed.toJSON();

      expect(data.footer.text).toContain('abc1234');
      expect(data.footer.text).toContain('Aaron Carlisle');
    });

    it('strips AI attributions from commit message', () => {
      const message = `feat: add feature

Some description

Co-Authored-By: Claude <noreply@anthropic.com>`;
      const embed = buildCommitEmbed('abc1234', message, 'user/repo');
      const data = embed.toJSON();

      expect(data.title).toBe('feat: add feature');
      expect(data.description).toBe('Some description');
      expect(data.description).not.toContain('Co-Authored-By');
    });
  });

  describe('buildReleaseEmbed', () => {
    it('creates embed with version and title', () => {
      const release = {
        version: '1.0.0',
        title: 'Initial Release',
        highlights: ['Feature 1', 'Feature 2'],
      };
      const embed = buildReleaseEmbed(release);
      const data = embed.toJSON();

      expect(data.title).toBe('v1.0.0 — Initial Release');
    });

    it('includes highlights as a field', () => {
      const release = {
        version: '1.0.0',
        title: 'Test Release',
        highlights: ['Highlight 1', 'Highlight 2'],
      };
      const embed = buildReleaseEmbed(release);
      const data = embed.toJSON();

      const highlightsField = data.fields.find(f => f.name === 'Highlights');
      expect(highlightsField).toBeDefined();
      expect(highlightsField.value).toContain('• Highlight 1');
      expect(highlightsField.value).toContain('• Highlight 2');
    });

    it('handles empty highlights', () => {
      const release = {
        version: '1.0.0',
        title: 'No Highlights',
        highlights: [],
      };
      const embed = buildReleaseEmbed(release);
      const data = embed.toJSON();

      const highlightsField = data.fields.find(f => f.name === 'Highlights');
      expect(highlightsField).toBeUndefined();
    });

    it('includes link to full release notes', () => {
      const release = {
        version: '1.0.0',
        title: 'Test',
        highlights: [],
      };
      const embed = buildReleaseEmbed(release);
      const data = embed.toJSON();

      const linkField = data.fields.find(f => f.value && f.value.includes('Release Notes'));
      expect(linkField).toBeDefined();
    });
  });
});
