import { describe, it, expect } from 'vitest';
import { existsSync } from 'fs';
import {
  stripAIAttributions,
  parseReleaseNotes,
  buildCommitEmbed,
  buildReleaseEmbed,
  getCommitTypeColor,
  summarizeBody,
  AI_ATTRIBUTION_PATTERNS,
  COMMIT_TYPE_COLORS,
  DISCORD_TITLE_LIMIT,
  DISCORD_DESCRIPTION_LIMIT,
  TRUNCATION_MESSAGE_RESERVE,
  RELEASE_NOTES_PATH,
} from './discord-changelog.js';

describe('discord-changelog', () => {
  describe('stripAIAttributions', () => {
    it('removes Claude co-author lines', () => {
      const input = `feat: add feature

Some description

Co-Authored-By: Claude <noreply@anthropic.com>`;
      const result = stripAIAttributions(input);
      expect(result).toBe('feat: add feature\n\nSome description');
    });

    it('removes Anthropic domain co-author lines', () => {
      const input = `fix: bug fix

Co-Authored-By: AI Assistant <assistant@anthropic.com>`;
      const result = stripAIAttributions(input);
      expect(result).toBe('fix: bug fix');
    });

    it('removes GitHub Copilot co-author lines', () => {
      const input = `refactor: cleanup

Co-Authored-By: GitHub Copilot`;
      const result = stripAIAttributions(input);
      expect(result).toBe('refactor: cleanup');
    });

    it('removes "Generated with Claude Code" lines', () => {
      const input = `docs: update readme

Generated with Claude Code`;
      const result = stripAIAttributions(input);
      expect(result).toBe('docs: update readme');
    });

    it('removes "Generated by Claude" lines', () => {
      const input = `test: add tests

Generated by Claude`;
      const result = stripAIAttributions(input);
      expect(result).toBe('test: add tests');
    });

    it('removes emoji-prefixed Claude Code attribution', () => {
      const input = `feat: new feature

\ud83e\udd16 Generated with [Claude Code]`;
      const result = stripAIAttributions(input);
      expect(result).toBe('feat: new feature');
    });

    it('removes "Generated with Cursor" lines', () => {
      const input = `style: format code

Generated with Cursor`;
      const result = stripAIAttributions(input);
      expect(result).toBe('style: format code');
    });

    it('removes "Generated by Copilot" lines', () => {
      const input = `chore: update deps

Generated by Copilot`;
      const result = stripAIAttributions(input);
      expect(result).toBe('chore: update deps');
    });

    it('removes multiple AI attributions in one message', () => {
      const input = `feat: complex feature

This is a detailed description.

Co-Authored-By: Claude <noreply@anthropic.com>
Generated with Claude Code`;
      const result = stripAIAttributions(input);
      expect(result).toBe('feat: complex feature\n\nThis is a detailed description.');
    });

    it('collapses multiple consecutive blank lines', () => {
      const input = `feat: feature



Multiple blank lines above`;
      const result = stripAIAttributions(input);
      expect(result).toBe('feat: feature\n\nMultiple blank lines above');
    });

    it('handles messages with no AI attributions', () => {
      const input = `feat: regular commit

This has no AI attribution.`;
      const result = stripAIAttributions(input);
      expect(result).toBe('feat: regular commit\n\nThis has no AI attribution.');
    });

    it('handles empty messages', () => {
      const result = stripAIAttributions('');
      expect(result).toBe('');
    });

    it('handles messages that are only AI attribution', () => {
      const input = 'Co-Authored-By: Claude <noreply@anthropic.com>';
      const result = stripAIAttributions(input);
      expect(result).toBe('');
    });

    it('is case insensitive for pattern matching', () => {
      const input = `feat: feature

CO-AUTHORED-BY: CLAUDE <noreply@ANTHROPIC.COM>`;
      const result = stripAIAttributions(input);
      expect(result).toBe('feat: feature');
    });

    it('preserves legitimate co-authors without AI keywords', () => {
      const input = `feat: collaborative feature

Co-Authored-By: John Smith <john@example.com>`;
      const result = stripAIAttributions(input);
      expect(result).toBe('feat: collaborative feature\n\nCo-Authored-By: John Smith <john@example.com>');
    });

    // Note: The patterns intentionally use broad matching per CLAUDE.md policy.
    // This means names containing "claude" or "anthropic" will be stripped even
    // if they belong to legitimate humans (e.g., "Claude Smith"). This is an
    // accepted trade-off for aggressive AI attribution removal.
    it('strips co-authors with AI keywords in name (known aggressive behavior)', () => {
      const input = `feat: collaborative feature

Co-Authored-By: Claude Smith <claude.smith@example.com>`;
      const result = stripAIAttributions(input);
      // This IS stripped because "claude" appears in the name - intentional per CLAUDE.md
      expect(result).toBe('feat: collaborative feature');
    });
  });

  describe('constants', () => {
    it('DISCORD_TITLE_LIMIT is 256', () => {
      expect(DISCORD_TITLE_LIMIT).toBe(256);
    });

    it('DISCORD_DESCRIPTION_LIMIT is 500 for concise posts', () => {
      expect(DISCORD_DESCRIPTION_LIMIT).toBe(500);
    });

    it('TRUNCATION_MESSAGE_RESERVE is 50', () => {
      expect(TRUNCATION_MESSAGE_RESERVE).toBe(50);
    });

    it('has 7 AI attribution patterns', () => {
      expect(AI_ATTRIBUTION_PATTERNS).toHaveLength(7);
    });

    it('has commit type colors for common types', () => {
      expect(COMMIT_TYPE_COLORS.feat).toBe(0x10b981);
      expect(COMMIT_TYPE_COLORS.fix).toBe(0xef4444);
      expect(COMMIT_TYPE_COLORS.docs).toBe(0x3b82f6);
    });
  });

  describe('parseReleaseNotes', () => {
    it('returns parsed release notes from the actual file', () => {
      // This tests against the actual releaseNotes.ts file
      const result = parseReleaseNotes();

      expect(result).not.toBeNull();
      expect(result.currentVersion).toMatch(/^\d+\.\d+\.\d+$/);
      expect(result.latestRelease).toBeDefined();
      expect(result.latestRelease.version).toMatch(/^\d+\.\d+\.\d+$/);
      expect(result.latestRelease.date).toMatch(/^\d{4}-\d{2}-\d{2}$/);
      expect(Array.isArray(result.latestRelease.highlights)).toBe(true);
    });

    it('RELEASE_NOTES_PATH points to an existing file', () => {
      expect(existsSync(RELEASE_NOTES_PATH)).toBe(true);
    });

    it('currentVersion matches latestRelease.version', () => {
      const result = parseReleaseNotes();
      expect(result.currentVersion).toBe(result.latestRelease.version);
    });
  });

  describe('buildCommitEmbed', () => {
    it('creates embed with title from commit message', () => {
      const embed = buildCommitEmbed('abc1234567890', 'feat: add new feature', 'user/repo');
      const data = embed.toJSON();

      expect(data.title).toBe('feat: add new feature');
      expect(data.url).toBe('https://github.com/user/repo/commit/abc1234567890');
    });

    it('uses green color for feat commits', () => {
      const embed = buildCommitEmbed('abc1234', 'feat: add new feature', 'user/repo');
      const data = embed.toJSON();

      expect(data.color).toBe(0x10b981);
    });

    it('uses red color for fix commits', () => {
      const embed = buildCommitEmbed('abc1234', 'fix: repair bug', 'user/repo');
      const data = embed.toJSON();

      expect(data.color).toBe(0xef4444);
    });

    it('truncates long titles to 256 characters', () => {
      const longTitle = 'a'.repeat(300);
      const embed = buildCommitEmbed('abc1234', longTitle, 'user/repo');
      const data = embed.toJSON();

      expect(data.title.length).toBeLessThanOrEqual(DISCORD_TITLE_LIMIT);
      expect(data.title.endsWith('...')).toBe(true);
    });

    it('uses shortSha as fallback when message is empty', () => {
      const embed = buildCommitEmbed('abc1234567890', '', 'user/repo');
      const data = embed.toJSON();

      expect(data.title).toBe('abc1234');
    });

    it('uses shortSha as fallback when message is only AI attribution', () => {
      const embed = buildCommitEmbed('abc1234567890', 'Co-Authored-By: Claude <noreply@anthropic.com>', 'user/repo');
      const data = embed.toJSON();

      expect(data.title).toBe('abc1234');
    });

    it('includes commit body as description', () => {
      const message = `feat: add feature

This is the commit body with more details.`;
      const embed = buildCommitEmbed('abc1234', message, 'user/repo');
      const data = embed.toJSON();

      expect(data.description).toBe('This is the commit body with more details.');
    });

    it('summarizes long descriptions', () => {
      const longBody = 'x'.repeat(600);
      const message = `feat: title\n\n${longBody}`;
      const embed = buildCommitEmbed('abc1234', message, 'user/repo');
      const data = embed.toJSON();

      expect(data.description.length).toBeLessThanOrEqual(DISCORD_DESCRIPTION_LIMIT);
    });

    it('sets footer with short SHA and author', () => {
      const embed = buildCommitEmbed('abc1234567890', 'feat: test', 'user/repo');
      const data = embed.toJSON();

      expect(data.footer.text).toContain('abc1234');
      expect(data.footer.text).toContain('Aaron Carlisle');
    });

    it('strips AI attributions from commit message', () => {
      const message = `feat: add feature

Some description

Co-Authored-By: Claude <noreply@anthropic.com>`;
      const embed = buildCommitEmbed('abc1234', message, 'user/repo');
      const data = embed.toJSON();

      expect(data.title).toBe('feat: add feature');
      expect(data.description).toBe('Some description');
      expect(data.description).not.toContain('Co-Authored-By');
    });
  });

  describe('getCommitTypeColor', () => {
    it('returns green for feat commits', () => {
      expect(getCommitTypeColor('feat: add feature')).toBe(0x10b981);
    });

    it('returns red for fix commits', () => {
      expect(getCommitTypeColor('fix: repair bug')).toBe(0xef4444);
    });

    it('returns blue for docs commits', () => {
      expect(getCommitTypeColor('docs: update readme')).toBe(0x3b82f6);
    });

    it('handles scoped commits', () => {
      expect(getCommitTypeColor('feat(ui): add button')).toBe(0x10b981);
      expect(getCommitTypeColor('fix(api): handle error')).toBe(0xef4444);
    });

    it('returns default gray for unknown types', () => {
      expect(getCommitTypeColor('random commit message')).toBe(0x6b7280);
    });

    it('is case insensitive', () => {
      expect(getCommitTypeColor('FEAT: uppercase feature')).toBe(0x10b981);
      expect(getCommitTypeColor('FIX: uppercase fix')).toBe(0xef4444);
    });
  });

  describe('summarizeBody', () => {
    it('returns body as-is if under max length', () => {
      const body = 'Short body text.';
      expect(summarizeBody(body, 500)).toBe('Short body text.');
    });

    it('returns empty string for empty body', () => {
      expect(summarizeBody('', 500)).toBe('');
      expect(summarizeBody(null, 500)).toBe(null);
    });

    it('prioritizes bullet points when present', () => {
      const body = `Some intro text.

- First bullet point
- Second bullet point
- Third bullet point

Some outro text.`;
      const result = summarizeBody(body, 100);
      expect(result).toContain('First bullet');
    });

    it('normalizes different bullet styles to dots', () => {
      const body = `* Star bullet
- Dash bullet`;
      const result = summarizeBody(body, 500);
      expect(result).toContain('Star bullet');
      expect(result).toContain('Dash bullet');
    });

    it('truncates at sentence boundary when no bullets', () => {
      const body = 'First sentence here. Second sentence here. Third sentence is much longer and continues.';
      const result = summarizeBody(body, 60);
      expect(result).toContain('First sentence');
    });

    it('enforces strict character limit', () => {
      const longBody = 'x'.repeat(600);
      const result = summarizeBody(longBody, 100);
      expect(result.length).toBeLessThanOrEqual(100);
      expect(result.endsWith('...')).toBe(true);
    });
  });

  describe('buildReleaseEmbed', () => {
    it('creates embed with version and title', () => {
      const release = {
        version: '1.0.0',
        title: 'Initial Release',
        highlights: ['Feature 1', 'Feature 2'],
      };
      const embed = buildReleaseEmbed(release);
      const data = embed.toJSON();

      expect(data.title).toBe('v1.0.0 — Initial Release');
    });

    it('includes highlights in description', () => {
      const release = {
        version: '1.0.0',
        title: 'Test Release',
        highlights: ['Highlight 1', 'Highlight 2'],
      };
      const embed = buildReleaseEmbed(release);
      const data = embed.toJSON();

      expect(data.description).toContain('• Highlight 1');
      expect(data.description).toContain('• Highlight 2');
    });

    it('handles empty highlights', () => {
      const release = {
        version: '1.0.0',
        title: 'No Highlights',
        highlights: [],
      };
      const embed = buildReleaseEmbed(release);
      const data = embed.toJSON();

      // Should still have the link to release notes
      expect(data.description).toContain('View Full Release Notes');
    });

    it('includes link to full release notes in description', () => {
      const release = {
        version: '1.0.0',
        title: 'Test',
        highlights: [],
      };
      const embed = buildReleaseEmbed(release);
      const data = embed.toJSON();

      expect(data.description).toContain('View Full Release Notes');
    });

    it('uses teal accent color', () => {
      const release = {
        version: '1.0.0',
        title: 'Test',
        highlights: [],
      };
      const embed = buildReleaseEmbed(release);
      const data = embed.toJSON();

      expect(data.color).toBe(0x14b8a6);
    });
  });

  describe('embed combinations', () => {
    it('can build both release and commit embeds for the same message', () => {
      // Simulates scenario where a version bump commit triggers both embeds
      const release = {
        version: '1.0.5',
        title: 'New Features',
        highlights: ['Feature A', 'Feature B'],
      };
      const commitMessage = `chore: bump version to 1.0.5

- Added Feature A
- Added Feature B`;

      const releaseEmbed = buildReleaseEmbed(release);
      const commitEmbed = buildCommitEmbed('abc1234', commitMessage, 'user/repo');

      const releaseData = releaseEmbed.toJSON();
      const commitData = commitEmbed.toJSON();

      // Both embeds should be valid and have distinct content
      expect(releaseData.title).toBe('v1.0.5 — New Features');
      expect(commitData.title).toBe('chore: bump version to 1.0.5');

      // Release embed has teal color, commit embed has gray (chore type)
      expect(releaseData.color).toBe(0x14b8a6);
      expect(commitData.color).toBe(0x6b7280);
    });

    it('release and commit embeds have compatible structure for Discord API', () => {
      const release = {
        version: '2.0.0',
        title: 'Major Release',
        highlights: ['Breaking changes'],
      };
      const releaseEmbed = buildReleaseEmbed(release);
      const commitEmbed = buildCommitEmbed('def5678', 'feat: major update', 'owner/repo');

      // Both should be valid EmbedBuilder instances that can be sent together
      const embeds = [releaseEmbed, commitEmbed];

      // Verify each embed has required structure
      embeds.forEach((embed) => {
        const data = embed.toJSON();
        expect(data).toHaveProperty('title');
        expect(data).toHaveProperty('color');
        expect(typeof data.title).toBe('string');
        expect(typeof data.color).toBe('number');
      });
    });
  });
});
